const EXCEPTIONS = {
    INVALID_DATE: 'INVALID_DATE',
    INVALID_NAME: 'INVALID_NAME',
    INVALID_EMAIL: 'INVALID_EMAIL',
    INVALID_DATE_OF_BIRTH: 'INVALID_DATE_OF_BIRTH',
    REPOSITORY_ERROR: 'REPOSITORY_ERROR',
}

export { EXCEPTIONS }
